Test-IOMundo/Models/ErrorViewModel.cs
namespace Test_IOMundo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Test-IOMundo/Models/Offer.cs
namespace Test_IOMundo.Models
{
    public class Offer
    {
        public string Id { get; set; }
        public DateTime CheckInDate { get; set; }
        public int StayDurationNights { get; set; }
        public string PersonCombination { get; set; }
        public string ServiceCode { get; set; }
        public int Price { get; set; }
        public int PricePerAdult { get; set; }
        public int PricePerChild { get; set; }
        public int StrikePrice { get; set; }
        public int StrikePricePerAdult { get; set; }

        public int StrikePricePerChild { get; set; }
        public bool ShowStrikePrice { get; set; }
        public DateTime LastUpdated { get; set; }

    }
}

Test-IOMundo/Models/Price.cs
namespace Test_IOMundo.Models
{
    public class Price
    {
        public Price() { }
        public Price(int adultDayPrice, int childDayPrice)
        {
            OneDayPricePerAdult = adultDayPrice;
            OneDayPricePerChild = childDayPrice;
        }
        public int TotalPrice { get; set; } = 0;
        public int PricePerAdult { get; set; } = 0;
        public int PricePerChild { get; set; } = 0;
        public int OneDayPricePerAdult { get; } = 100;
        public int OneDayPricePerChild { get; } = 50;

        public int calculateTotalPrice()
        {
            return PricePerAdult + PricePerChild;
        }
    }
}

Test-IOMundo/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace Test_IOMundo.Models
{
    public class User : IdentityUser
    {
        public string Name { get; set; }
    }
}

Test-IOMundo/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Test_IOMundo.ViewModels
{
    public class LoginViewModel
    {
        [Display(Name = "User name")]
        [Required(ErrorMessage = "User name is required")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Test-IOMundo/ViewModels/RequestObject.cs
using System.ComponentModel.DataAnnotations;

namespace Test_IOMundo.ViewModels
{
    public class RequestObject
    {
        [Display(Name = "Check-In Date")]
        [Required(ErrorMessage = "Date is required")]
        public DateTime DateForm { get; set; }

        [Display(Name = "Duration")]
        [Required(ErrorMessage = "Duration is required")]
        public int Duration { get; set; }

        [Display(Name = "Person Count")]
        [Required(ErrorMessage = "Person Count is required")]
        public string PersonCombination { get; set; }
        public LoginViewModel LoginViewModel { get; set; }
    }
}

Test-IOMundo/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Test_IOMundo.Data;
using Test_IOMundo.Interfaces;
using Test_IOMundo.Models;
using Test_IOMundo.ViewModels;

namespace Test_IOMundo.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountRepository _accountRepository;

        public AccountController(IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
        }
        public IActionResult Login()
        {
            var response = new LoginViewModel();
            return View(response);
        }

        [HttpPost]
        public async Task<bool> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid) return false;

            return await _accountRepository.Login(loginViewModel);
        }
    }
}

Test-IOMundo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Test_IOMundo.Models;

namespace Test_IOMundo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Test-IOMundo/Controllers/OfferController.cs
using Microsoft.AspNetCore.Mvc;
using Test_IOMundo.Interfaces;
using Test_IOMundo.Models;
using Test_IOMundo.ViewModels;

namespace Test_IOMundo.Controllers
{
    public class OfferController : Controller
    {
        private readonly IOfferRepository _offerRepository;
        private readonly IAccountRepository _accountRepository;

        public OfferController(IOfferRepository offerRepository, IAccountRepository accountRepository)
        {
            _offerRepository = offerRepository;
            _accountRepository = accountRepository;
        }
        public async Task<IActionResult?> SearchAvailability(RequestObject requestObject)
        {
            if (!ModelState.IsValid) return View();

            if (await _accountRepository.Login(requestObject.LoginViewModel) == false) return View();

            IEnumerable<Offer> offers = await _offerRepository.GetByRequstObject(requestObject);
            return View(offers);
        }
    }
}

Test-IOMundo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Test-IOMundo/Views/Offer/SearchAvailability.cshtml
@using Test_IOMundo.ViewModels
@model LoginViewModel

<div>
    <h1>Search Availability Page Login</h1>

    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-action="SearchAvailability">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control">
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input class="btn btn-outline-success float right" type="submit" value="Log in" />
                    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Test-IOMundo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test_IOMundo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Test_IOMundo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Test_IOMundo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="SearchAvailability">Search Availability</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Test_IOMundo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>